/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconChatSquare: typeof import('@element-plus/icons-vue')['ChatSquare']
    ElIconCloseBold: typeof import('@element-plus/icons-vue')['CloseBold']
    ElIconDelete: typeof import('@element-plus/icons-vue')['Delete']
    ElIconEditPen: typeof import('@element-plus/icons-vue')['EditPen']
    ElIconSelect: typeof import('@element-plus/icons-vue')['Select']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
  }
}
